module.exports = {
  preset: "jest-expo",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  testEnvironment: "jsdom",
  transformIgnorePatterns: [
    "node_modules/(?!(jest-)?react-native|@react-native(-community)?|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@clerk/clerk-expo|@sentry/react-native|pressto|zustand|@shopify/.*|loglayer)",
  ],
  collectCoverageFrom: [
    "**/*.{js,jsx,ts,tsx}",
    "!**/*.d.ts",
    "!**/coverage/**",
    "!**/node_modules/**",
    "!**/babel.config.js",
    "!**/expo-env.d.ts",
    "!**/.expo/**",
    "!**/assets/**",
    "!**/Design-Inspiration/**",
    "!**/app.json",
    "!**/eas.json",
    "!**/flow.yaml",
  ],
  coverageReporters: ["text", "lcov", "html"],
  coverageDirectory: "coverage",
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  moduleFileExtensions: ["ts", "tsx", "js", "jsx"],
  moduleDirectories: ["node_modules", "<rootDir>"],
  testMatch: ["**/__tests__/**/*.(ts|tsx|js)", "**/*.(test|spec).(ts|tsx|js)"],
  moduleNameMapping: {
    "^@/(.*)$": "<rootDir>/$1",
    "^@assets/(.*)$": "<rootDir>/assets/$1",
    "^@components/(.*)$": "<rootDir>/components/$1",
    "^@constants/(.*)$": "<rootDir>/constants/$1",
    "^@hooks/(.*)$": "<rootDir>/hooks/$1",
    "^@services/(.*)$": "<rootDir>/services/$1",
    "^@types/(.*)$": "<rootDir>/types/$1",
    "^@app/(.*)$": "<rootDir>/app/$1",
  },
  clearMocks: true,
  restoreMocks: true,
};
